### PR TITLE
Remove python 2 support

### PR DESCRIPTION
**Pull request by hanars**

### CODE REVIEW

**Comment by hanars** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- seqr/views/utils/pedigree_image_utils_tests.py  2
- seqr/views/apis/igv_api_tests.py  3
- seqr/views/utils/pedigree_info_utils_tests.py  7
- seqr/management/tests/run_postgres_database_backup_tests.py  1
- seqr/views/apis/analysis_group_api_tests.py  3
- seqr/views/apis/awesomebar_api_tests.py  1
- seqr/views/apis/auth_api_tests.py  1
- seqr/management/tests/run_settings_backup_tests.py  1
- seqr/views/utils/orm_to_json_utils_tests.py  4
- seqr/views/utils/export_utils_tests.py  7
- matchmaker/views/matchmaker_api_tests.py  4
- seqr/views/apis/users_api_tests.py  1
- seqr/views/apis/case_review_api_tests.py  1
- seqr/views/react_app_tests.py  2
- seqr/views/apis/project_categories_api_tests.py  3
- seqr/utils/redis_utils_tests.py  1
- seqr/views/apis/project_api_tests.py  2
- seqr/management/tests/check_bam_cram_paths_tests.py  1
- seqr/utils/xpos_utils_tests.py  1
- seqr/views/apis/variant_search_api_tests.py  2
- seqr/management/tests/lift_variant_to_hg38_tests.py  2
- seqr/views/apis/gene_api_tests.py  1
- matchmaker/views/external_api_tests.py  1
- seqr/management/tests/copy_project_tags_tests.py  2
- seqr/views/apis/staff_api_tests.py  1
- seqr/management/tests/reload_saved_variant_json_tests.py  3
- seqr/views/apis/locus_list_api_tests.py  3
- seqr/views/apis/dataset_api_tests.py  9
- seqr/views/apis/saved_variant_api_tests.py  11
- seqr/views/utils/file_utils_tests.py  5
- seqr/views/apis/family_api_tests.py  1
- seqr/management/tests/transfer_families_to_different_project_tests.py  1
- seqr/views/apis/individual_api_tests.py  5
- seqr/management/tests/lift_project_to_hg38_tests.py  6
- seqr/management/tests/resend_welcome_email_tests.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/hanars/seqr/pullRequest?prid=5908718&bid=19356944)

**Comment by ShifaSZ** [comment]
The name of file `seqr/utils/elasticsearch/es_utils_2_3_tests.py` needs to be changed.

**Comment by ShifaSZ** [comment]
https://github.com/macarthur-lab/seqr/blob/6f00db6d0627d98fc1d7342c0314ebb0071b5dad/seqr/utils/middleware.py#L36
Should the line be changed to as below?
```
exception_json = {'message': str(exception)}
```

**Comment by ShifaSZ** [comment]
https://github.com/macarthur-lab/seqr/blob/6f00db6d0627d98fc1d7342c0314ebb0071b5dad/seqr/views/utils/export_utils.py#L81-L83
These lines can be changed to:
```
content = str(content.encode('utf-8'), 'ascii', errors='ignore') # Strip unicode chars in the content
```

**Comment by ShifaSZ** [comment]
https://github.com/macarthur-lab/seqr/blob/6f00db6d0627d98fc1d7342c0314ebb0071b5dad/seqr/views/utils/pedigree_info_utils.py#L438
This line can be changed to:
```
row = {k: v.encode('ascii', errors='ignore').decode()
```

**Comment by hanars** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- matchmaker/views/external_api_tests.py  1
- seqr/management/tests/copy_project_tags_tests.py  2
- seqr/views/apis/variant_search_api_tests.py  2
- seqr/management/tests/reload_saved_variant_json_tests.py  3
- seqr/views/apis/awesomebar_api_tests.py  1
- seqr/views/utils/orm_to_json_utils_tests.py  4
- seqr/management/tests/check_bam_cram_paths_tests.py  1
- seqr/views/apis/case_review_api_tests.py  1
- seqr/utils/elasticsearch/es_utils_tests.py  19
- seqr/views/apis/auth_api_tests.py  1
- seqr/views/apis/project_api_tests.py  2
- seqr/views/apis/family_api_tests.py  1
- seqr/views/apis/dataset_api_tests.py  9
- seqr/views/utils/pedigree_info_utils_tests.py  7
- seqr/management/tests/run_settings_backup_tests.py  1
- seqr/views/apis/gene_api_tests.py  1
- seqr/views/apis/project_categories_api_tests.py  3
- seqr/utils/xpos_utils_tests.py  1
- seqr/views/utils/pedigree_image_utils_tests.py  2
- seqr/views/apis/igv_api_tests.py  3
- seqr/management/tests/run_postgres_database_backup_tests.py  1
- seqr/views/utils/file_utils_tests.py  5
- seqr/views/apis/locus_list_api_tests.py  3
- seqr/views/apis/saved_variant_api_tests.py  11
- seqr/management/tests/lift_project_to_hg38_tests.py  6
- seqr/views/apis/users_api_tests.py  1
- seqr/views/apis/individual_api_tests.py  5
- seqr/management/tests/resend_welcome_email_tests.py  3
- seqr/management/tests/lift_variant_to_hg38_tests.py  2
- seqr/management/tests/transfer_families_to_different_project_tests.py  1
- seqr/views/utils/export_utils_tests.py  7
- matchmaker/views/matchmaker_api_tests.py  4
- seqr/views/react_app_tests.py  2
- seqr/views/apis/staff_api_tests.py  1
- seqr/views/apis/analysis_group_api_tests.py  3
- seqr/utils/redis_utils_tests.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/hanars/seqr/pullRequest?prid=5908718&bid=19356944)

**Comment by hanars** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- seqr/views/apis/awesomebar_api_tests.py  1
- seqr/views/apis/analysis_group_api_tests.py  3
- seqr/views/utils/export_utils_tests.py  7
- seqr/management/tests/reload_saved_variant_json_tests.py  3
- seqr/management/tests/check_bam_cram_paths_tests.py  1
- seqr/views/utils/file_utils_tests.py  5
- seqr/utils/elasticsearch/es_utils_tests.py  19
- seqr/utils/redis_utils_tests.py  1
- matchmaker/views/external_api_tests.py  1
- seqr/management/tests/transfer_families_to_different_project_tests.py  1
- seqr/views/apis/staff_api_tests.py  1
- seqr/views/apis/family_api_tests.py  1
- seqr/views/utils/pedigree_image_utils_tests.py  2
- seqr/management/tests/lift_variant_to_hg38_tests.py  2
- seqr/management/tests/copy_project_tags_tests.py  2
- seqr/views/utils/orm_to_json_utils_tests.py  4
- seqr/views/utils/pedigree_info_utils_tests.py  7
- seqr/views/apis/igv_api_tests.py  3
- seqr/views/apis/auth_api_tests.py  1
- seqr/views/apis/saved_variant_api_tests.py  11
- seqr/management/tests/resend_welcome_email_tests.py  3
- seqr/views/apis/variant_search_api_tests.py  2
- seqr/views/apis/dataset_api_tests.py  9
- seqr/views/apis/case_review_api_tests.py  1
- seqr/views/apis/individual_api_tests.py  5
- matchmaker/views/matchmaker_api_tests.py  4
- seqr/management/tests/run_postgres_database_backup_tests.py  1
- seqr/views/react_app_tests.py  2
- seqr/views/apis/project_categories_api_tests.py  3
- seqr/management/tests/run_settings_backup_tests.py  1
- seqr/views/apis/gene_api_tests.py  1
- seqr/management/tests/lift_project_to_hg38_tests.py  6
- seqr/views/apis/users_api_tests.py  1
- seqr/utils/xpos_utils_tests.py  1
- seqr/views/apis/project_api_tests.py  2
- seqr/views/apis/locus_list_api_tests.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/hanars/seqr/pullRequest?prid=5908718&bid=19356944)

**Pull request merged**
